-- Create the bank_reviews schema (optional if you're using SYSTEM)
-- CREATE USER bank_reviews IDENTIFIED BY yourpassword;
-- GRANT CONNECT, RESOURCE TO bank_reviews;

-- Create the banks table
CREATE TABLE banks (
    bank_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR2(100) UNIQUE NOT NULL
);

-- Create the reviews table
CREATE TABLE reviews (
    review_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    bank_id NUMBER REFERENCES banks(bank_id),
    review_text CLOB,
    translated_review CLOB,
    rating NUMBER,
    review_date DATE,
    sentiment_label VARCHAR2(20),
    sentiment_score FLOAT
);